from enum import Enum

class TransactionType(Enum):
    DEBIT = 'DEBIT'
    CREDIT = 'CREDIT'

class PaidOff(Enum):
    FIDELITY_PAYMENT = 'INTERNET PAYMENT THANK'
    COSTCO_PAYMENT = 'ONLINE PAYMENT, THANK YOU'

class TransactionName(Enum):
    PAYPAL = 'PAYPAL '
    CPI = 'CPI'
    VC = 'VC'
    SQ = 'SQ '
    VENDING_MACHINE = 'VENDING MACHINE'
    VET = 'VET'
    STARBUCKSSE = 'STARBUCKSSE'
    STARBUCKS = 'STARBUCKS'
    AMAZON_PRIME = 'Amazon Prime'
    AMAZON = ('AMAZON', 'AMZN')
    COSTCO = 'COSTCO'
    A_CLIP_ABOVE = 'A CLIP ABOVE'
    GROOMER = 'GROOMER'
    WAX = 'EUROPEAN WAX CENTER'
    LIBERTY_MUTUAL = 'LIBERTY MUTUAL'
    RENTERS_INSURANCE = 'RENTERS INSURANCE'
    CAR_INSURANCE = 'CAR INSURANCE'
    ENT_CU = 'ENT CU'
    CAR_PAYMENT = 'CAR PAYMENT'
    PL = 'PL'
    RENT = 'RENT'
    DHHA = 'DENVER HEALTH AN'
    DENVER_HEALTH = 'DENVER HEALTH'
    AH = 'AH ROCKY MOUNTAI'
    ADVENT = 'ADVENT HEALTH'
    INTEREST_EARNED = 'INTEREST EARNED'
    INTEREST = 'INTEREST'
    HEALTH_ONE= 'HEALTHONE'
    SWEDISH = 'HEALTH ONE'
    DIRECT_DEPOSIT = 'Direct Deposit'
    COMCAST = 'COMCAST CABLE COMM'
    INTERNET = 'INTERNET'

class Category(Enum):
    INCOME = 'INCOME'
    UTILITIES = 'UTILITIES'
    FOOD = 'FOOD'
    CAR = 'CAR'
    HOUSING = 'HOUSING'
    SUBSCRIPTIONS = 'SUBSCRIPTIONS'
    MEDICAL = 'MEDICAL'
    PET = 'PET'
    OTHER = 'OTHER'
